---
title: "Quantified Self Analysis"
author: "C Hubbell"
date: "February 4, 2016"
output: html_document
---

## Introduction

It is now possible to collect a large amount of data about personal movement using activity monitoring devices such as a [Fitbit](http://www.fitbit.com), [Nike Fuelband](http://www.nike.com/us/en_us/c/nikeplus-fuelband), or [Jawbone Up](https://jawbone.com/up). These type of devices are part of the "quantified self" movement -- a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, because they are tech geeks, or maybe a little of each. 

This project makes use of data from a personal activity monitoring device. The device collects data at 5 minute intervals throughout the day. The data consists of two months of information from an anonymous individual collected during the months of October and November 2012 and include the number of steps taken in 5 minute intervals each day.

## Data

The data for this report can be downloaded from the following link and are also made available within this repository.

* Dataset: [Activity monitoring data](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip) [52K]

The variables included in the dataset are:

* **steps**: Number of steps taking in a 5-minute interval (missing
    values are coded as `NA`)
* **date**: The date on which the measurement was taken in YYYY-MM-DD
    format
* **interval**: Identifier for the 5-minute interval in which
    measurement was taken

The dataset is stored in a comma-separated-value (CSV) file and there are a total of 17,568 observations.

## Analysis

### Loading and preprocessing the data

We begin by unzipping the activity file. To run this script, the user must be sure the zip file is located in the working directory.

```{R echo=TRUE}
unzip("./activity.zip")
list.files() #to see what we unzipped
data<-read.csv("activity.csv")
head(data)
```

We see that `data` consists of 17,568 observations of 3 variables: steps, date, and interval. Some of the values for steps are missing (coded as NA). Now we process the data a bit to make our analysis easier.

From `str(data)` we see that the date variable is currently a factor variable. We will change it into a date variable.

```{R echo=TRUE}
data$date<-as.Date(as.character(data$date), format="%Y-%m-%d")
```

Finally we obtain a list of unique dates for use later.

```{R echo=TRUE}
dates<-unique(data$date)
```

Our dataset is processed and ready for our analysis.

### What is the mean total number of steps taken per day?

To calculate the mean total number of steps by day, we will ignore any missing values in the dataset.

```{R echo=TRUE}
totalsteps<-tapply(data$steps, data$date, sum, na.rm=TRUE)
totalsteps<-data.frame(date=dates,totalsteps=as.numeric(totalsteps))
```

Next we will plot a histogram of mean total steps. The plot generated by the code is shown directly below the code.

```{R echo=TRUE}
require(RColorBrewer)
hist(totalsteps$totalsteps, breaks=10, 
     main="Total Daily Steps", 
     xlab="Total Daily Steps", ylab="Number of Days", 
     col=brewer.pal(10,"PRGn"), 
     ylim=c(0,20), xlim=c(0,25000)
     )

```

Now we calculate the mean and median number of steps taken each day, again ignoring any NA values. The `View()` function allows us to see the entire data frame which is the result of our calculations.

```{R echo=TRUE}
meansteps<-tapply(data$steps, data$date, mean, na.rm=TRUE)
meansteps<-data.frame(date=dates,meansteps=as.numeric(meansteps))
View(meansteps, "Mean Steps By Day")

medsteps<-tapply(data$steps, data$date, median, na.rm=TRUE)
medsteps<-data.frame(date=dates,medsteps=as.numeric(medsteps))
View(medsteps, "Median Steps By Day")
```

The first few rows of each of the data frames are shown below:

```{R echo=TRUE}
head(meansteps)
```

```{R echo=TRUE}
head(medsteps)
```

From this we can see that some days the device was not worn or used or turned on (when the mean and median are both NA/NaN). We also see that across the five minute time intervals, the subject is most often sedentary as the median for most days is 0 steps. This is likely due to sleeping, driving, working, eating, and other activities that typically require a person to be sitting or laying down.

### What is the average daily activity pattern?

To determine the average daily activity pattern, we will build a time series plot. This plot shows the mean number of steps for each 5-minute time interval, ignoring any missing values (NA). The plot is shown below the code that generates it.

```{R echo=TRUE}
timeMeanSteps<-tapply(data$steps, data$interval, mean, na.rm=TRUE)

plot(timeMeanSteps,type="l",
     main="Mean Steps By Time Interval",
     xlab="Time Interval", ylab="Mean Steps"
     )
```

We are also interested in knowing which 5-minute time interval yields the maximum mean number of steps. The following code is used to determine that value.

```{R echo=TRUE}
intervals<-unique(data$interval)
timeMeanSteps<-data.frame(interval=intervals,meansteps=as.numeric(timeMeanSteps))

x<-which.max(timeMeanSteps$meansteps)
y<-timeMeanSteps[x,]$interval
```

The result is the 5-minute interval:

```{R echo=TRUE}
y
```

To determine the actual clock time corresponding to 835 minutes past midnight, we use the following:

```{R echo=TRUE}
strftime(as.POSIXct("1970-01-01") + as.difftime(y, units="mins"),"%H:%M")
```

or 1:55pm-2:00pm. 

### Imputing missing values

In our dataset, there are a number of days/intervals where there are missing values (coded as NA). The presence of missing days may introduce bias into some calculations or summaries of the data. First, we would like to know how many values are coded as NA as well as what percentage of the overall data is missing values.

```{R echo=TRUE}
sum(is.na(data$steps))
```

```{R echo=TRUE}
mean(is.na(data$steps))
```

There are 2304 total observations with missing values, which makes up just over 13% of the total observations. To correct for this, we devise a method of imputing values to replace NAs. The method is to use the mean number of steps corresponding to the 5-minute time interval for which the NA value appears. We will replace all NAs in a new data table called `complete` so that we can compare this data with the original data.

```{R echo=TRUE}
complete<-data

for(i in 1:length(complete$steps)){
  if(is.na(complete$steps[i])){
    complete$steps[i]<-timeMeanSteps[which(complete$interval[i] == timeMeanSteps$interval),]$meansteps
  }
}
```

The next task is to make a histogram of both the complete dataset (with no NA values) and the original dataset (with NA values). To make an accurate comparison, both histograms are plotted on the same scale. The colors are arbitrarily selected and merely add to the aesthetic value of the plot. The plot is shown directly below the code used to generate it.

```{R echo=TRUE}
totalstepscomplete<-tapply(complete$steps, complete$date, sum)
totalstepscomplete<-data.frame(date=dates,totalsteps=as.numeric(totalstepscomplete))

par(mfrow=c(1,2), cex=.8)

hist(totalsteps$totalsteps, breaks=10, 
     main="Total Daily Steps (Actual)",
     xlab="Total Daily Steps", ylab="Number of Days", 
     col=brewer.pal(9,"BuPu"), 
     ylim=c(0,25), xlim=c(0,25000)
)

hist(totalstepscomplete$totalsteps, breaks=10, 
     main="Total Daily Steps (NAs Replaced)", 
     xlab="Total Daily Steps", ylab="Number of Days", 
     col=brewer.pal(9,"BuPu"), 
     ylim=c(0,25), xlim=c(0,25000)
)

dev.off()
```

We would also like to calculate the new mean and median steps per day now that we have imputed values for the NAs to create the `complete` dataset.

```{R echo=TRUE}
meanstepscomplete<-tapply(complete$steps, complete$date, mean)
meanstepscomplete<-data.frame(date=dates,meansteps=as.numeric(meanstepscomplete))
View(meanstepscomplete, "Mean Steps By Day (NAs Replaced")
```

```{R echo=TRUE}
medstepscomplete<-tapply(complete$steps, complete$date, median)
medstepscomplete<-data.frame(date=dates,medsteps=as.numeric(medstepscomplete))
View(medstepscomplete, "Median Steps By Day (NAs Replaced")
```

The first six observations for both the mean and median of the complete dataset are shown below. While the mean did not change significantly, the median is quite skewed by the replaced values. 

```{R echo=TRUE}
head(meanstepscomplete)
```

```{R echo=TRUE}
head(medstepscomplete)
```


### Are there differences in activity patterns between weekdays and weekends?

To compare the category of day (weekdays versus weekends), we use the ```complete``` dataset which has all NA values replaced by the mean steps of the corresponding time interval. We first create a new factor variable for the day's category (weekday or weekend) and then build a panel plot separating the two categories. The plot is shown below the code that generates it.

```{R echo=TRUE}
complete$day<-weekdays(complete$date)
complete$category[(complete$day=="Saturday" | complete$day=="Sunday")]<-"weekend"
complete$category[!(complete$day=="Saturday" | complete$day=="Sunday")]<-"weekday"

par(mfrow = c(2, 1))
for (type in c("weekend", "weekday")) {
  x <- aggregate(steps ~ interval, 
                 data = complete, 
                 subset = complete$category == type, 
                 FUN = mean)
  plot(x, type = "l", main = type)
}
dev.off()
```

While the plots for weekdays versus weekends differ, it is impossible for us to say why this might be the case without more information about the subject, his/her daily routine, sleep habits, hobbies, profession, etc.


